default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: simple-vue-kustomize
    destination:
      namespace: user1-bgd
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/ultrajeff/simple-vue-kustomize.git
      targetRevision: main
applications:
  helm-repos:
    source:
      path: ./helm-chart-repository.yaml